# Generated by Django 3.2.16 on 2022-11-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('number', 'career')},
        ),
    ]
