# Generated by Django 3.2.16 on 2022-11-08 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20221107_1736'),
        ('teachers', '0002_auto_20221107_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject', to='subjects.subject'),
        ),
    ]
