# Generated by Django 3.2.16 on 2022-11-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20221107_1736'),
        ('teachers', '0003_alter_teachersubject_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='subjects.area'),
        ),
    ]
