# Generated by Django 3.2.16 on 2022-11-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
        ('subjects', '0003_auto_20221107_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='careers.career'),
        ),
        migrations.AddField(
            model_name='subject',
            name='module_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
