# Generated by Django 3.2.16 on 2022-11-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20221110_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='key_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
