# Generated by Django 3.2.16 on 2022-11-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_schedule_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='shift',
            field=models.IntegerField(choices=[(1, 'Mañana'), (2, 'Tarde')], default=1),
        ),
    ]
