# Generated by Django 3.2.16 on 2022-11-14 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_group_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='school_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schedules.schoolperiod'),
        ),
    ]
