# Generated by Django 3.2.16 on 2022-11-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_alter_group_school_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schedules.group'),
        ),
    ]
