# Generated by Django 3.2.16 on 2022-11-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_alter_schedule__class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('_class', 'day')},
        ),
    ]
