# Generated by Django 3.2.16 on 2022-11-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
    ]
