# Generated by Django 3.2.16 on 2022-11-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('_class', 'day'), name='name of constraint'),
        ),
    ]
