# Generated by Django 3.2.16 on 2022-11-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_schedule_name of constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='name of constraint',
        ),
    ]
